"""Scientific categories and provenance contracts for external test fixtures."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
import hashlib
import json
from pathlib import Path
import re


class FixtureCategory(StrEnum):
    ISSUE_PATCH_CORRECTNESS = "issue_patch_correctness"
    AI_ASSISTED_TRACE = "ai_assisted_trace"
    SECURITY_ANALYZER_ORACLE = "security_analyzer_oracle"
    CLEAN_CONTROL = "clean_control"
    ADVERSARIAL_INTEGRITY = "adversarial_integrity"


class GroundTruthScope(StrEnum):
    PATCH_AND_TEST_OUTCOME = "patch_and_test_outcome"
    AI_LINK_ASSOCIATION = "ai_link_association"
    ANALYZER_EXPECTATION = "analyzer_expectation"
    CONTROLLED_NEGATIVE = "controlled_negative"
    INTEGRITY_EXPECTATION = "integrity_expectation"


@dataclass(frozen=True)
class TestFixtureRecord:
    __test__ = False

    dataset_id: str
    record_id: str
    category: FixtureCategory
    ground_truth_scope: GroundTruthScope
    source_url: str
    source_revision: str
    license: str
    payload_hash: str
    local_path: str
    label_limitations: str
    authorship_label: str | None = None

    @classmethod
    def from_dict(cls, values: dict[str, object]) -> "TestFixtureRecord":
        payload = dict(values)
        payload["category"] = FixtureCategory(str(payload["category"]))
        payload["ground_truth_scope"] = GroundTruthScope(str(payload["ground_truth_scope"]))
        return cls(**payload)

    def to_dict(self) -> dict[str, object]:
        return {
            **self.__dict__,
            "category": self.category.value,
            "ground_truth_scope": self.ground_truth_scope.value,
        }


def canonical_hash(payload: object) -> str:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    return hashlib.sha256(encoded).hexdigest()


def _slug(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9._-]+", "-", value).strip("-")


def categorize_swebench_row(
    row: dict[str, object],
    *,
    source_revision: str = "6ec7bb89b9342f664a54a6e0a6ea6501d3437cc2",
) -> TestFixtureRecord:
    record_id = str(row.get("instance_id", "")).strip()
    if not record_id or not row.get("base_commit"):
        raise ValueError("SWE-bench rows require instance_id and base_commit")
    return TestFixtureRecord(
        dataset_id="swebench-lite",
        record_id=record_id,
        category=FixtureCategory.ISSUE_PATCH_CORRECTNESS,
        ground_truth_scope=GroundTruthScope.PATCH_AND_TEST_OUTCOME,
        source_url="https://huggingface.co/datasets/princeton-nlp/SWE-bench_Lite",
        source_revision=source_revision,
        license="source-repository-specific",
        payload_hash=canonical_hash(row),
        local_path=f"swebench/{_slug(record_id)}.json",
        label_limitations=(
            "Accepted issue/patch/test outcome; not an authorship, security, or universal quality label."
        ),
    )


def categorize_devgpt_row(
    row: dict[str, object],
    *,
    source_revision: str = "685efd2509dede9a6e996b839ae4e20d33430648",
) -> TestFixtureRecord:
    mentioned = str(row.get("MentionedURL", "")).strip()
    shared = str(row.get("URL", "")).strip()
    if not mentioned or not shared:
        raise ValueError("DevGPT rows require URL and MentionedURL")
    record_id = hashlib.sha256(f"{shared}\x1f{mentioned}".encode()).hexdigest()[:20]
    return TestFixtureRecord(
        dataset_id="devgpt",
        record_id=record_id,
        category=FixtureCategory.AI_ASSISTED_TRACE,
        ground_truth_scope=GroundTruthScope.AI_LINK_ASSOCIATION,
        source_url="https://github.com/NAIST-SE/DevGPT",
        source_revision=source_revision,
        license="NOASSERTION",
        payload_hash=canonical_hash(row),
        local_path=f"devgpt/{record_id}.json",
        label_limitations=(
            "A shared ChatGPT link is associated with a development artifact; this is not proof "
            "that linked code was generated by AI. Metadata-only research use pending license review."
        ),
    )


def categorize_codeql_file(
    *,
    path: str,
    content: str,
    source_revision: str = "87c77cc26ccd1d2d9791b8563be6d425ccdf0874",
) -> TestFixtureRecord:
    if not path or not content:
        raise ValueError("CodeQL fixtures require path and content")
    record_id = _slug(path)
    return TestFixtureRecord(
        dataset_id="codeql-python-tests",
        record_id=record_id,
        category=FixtureCategory.SECURITY_ANALYZER_ORACLE,
        ground_truth_scope=GroundTruthScope.ANALYZER_EXPECTATION,
        source_url=f"https://github.com/github/codeql/blob/{source_revision}/{path}",
        source_revision=source_revision,
        license="MIT",
        payload_hash=hashlib.sha256(content.encode()).hexdigest(),
        local_path=f"codeql/{record_id}.json",
        label_limitations=(
            "CodeQL query-test fixture for analyzer behavior; not a universal vulnerability label."
        ),
    )


def validate_fixture_catalog(records: tuple[TestFixtureRecord, ...]) -> tuple[TestFixtureRecord, ...]:
    seen: set[tuple[str, str]] = set()
    for item in records:
        key = (item.dataset_id, item.record_id)
        if key in seen:
            raise ValueError(f"duplicate fixture record: {key}")
        seen.add(key)
        if not re.fullmatch(r"[0-9a-f]{64}", item.payload_hash):
            raise ValueError(f"fixture {key} needs a lowercase SHA-256 payload hash")
        if not item.source_revision or not item.source_url.startswith("https://"):
            raise ValueError(f"fixture {key} lacks immutable source provenance")
        if item.authorship_label is not None and item.ground_truth_scope in {
            GroundTruthScope.AI_LINK_ASSOCIATION,
            GroundTruthScope.PATCH_AND_TEST_OUTCOME,
            GroundTruthScope.ANALYZER_EXPECTATION,
        }:
            raise ValueError(f"fixture {key} cannot support an authorship label")
    return records


def verify_fetched_fixtures(
    root: Path,
    records: tuple[TestFixtureRecord, ...],
) -> tuple[TestFixtureRecord, ...]:
    """Verify each cached payload against its catalog hash without trusting paths."""
    root = root.resolve()
    for item in validate_fixture_catalog(records):
        path = (root / item.local_path).resolve()
        if root not in path.parents:
            raise ValueError(f"fixture path escapes root: {item.local_path}")
        if not path.is_file():
            raise ValueError(f"fixture payload missing: {item.local_path}")
        payload = json.loads(path.read_text(encoding="utf-8"))
        observed = (
            hashlib.sha256(str(payload.get("content", "")).encode()).hexdigest()
            if item.category is FixtureCategory.SECURITY_ANALYZER_ORACLE
            else canonical_hash(payload)
        )
        if observed != item.payload_hash:
            raise ValueError(f"payload hash mismatch: {item.dataset_id}/{item.record_id}")
    return records
